### PR TITLE
validate returning ValidationError

### LINKED ISSUE #8: Return structured errors to clients
Clients calling cluster-validator from code should receive more structured errors that include the reason and resource.
For example, if pod validation failed, the client should receive a ValidationError object instead of a generic error.

The use case from the client side could be to output some information in why the failure occurred.
For example, dump logs from a pod, or other output that helps debug the reason.

Currently we provide a simple message

### PR DESCRIPTION
**Pull request by garomonegro**
Closes #8

### CODE REVIEW

File: pkg/client/validator.go [hunk 1]
```diff
@@ -29,11 +29,13 @@ import (
 )
 
 var (
-	successEmoji = emoji.Sprint(":check_mark_button:")
-	failEmoji    = emoji.Sprint(":fire:")
+	successEmoji                         = emoji.Sprint(":check_mark_button:")
+	failEmoji                            = emoji.Sprint(":fire:")
+	ValidationFailed    ValidationStatus = "failed"
```
Comment (eytan-avisror) [inline pkg/client/validator.go:34]: Can we change these to be constants?

File: pkg/client/validator.go [hunk 2]
```diff
@@ -99,19 +103,30 @@ func (v *Validator) Validate() error {
...
+				Message:   err,
+				Summaries: summaries,
+			}
 		}
 	}
 
-	return nil
+	return ValidationError{
+		Status:    ValidationSucceeded,
+		Message:   errors.Errorf("test"),
```
Comment (eytan-avisror) [inline pkg/client/validator.go:127]: should be err here instead?

**Comment by eytan-avisror** [comment]
Do we also need to address the command execution (cmd/validate.go) to make sure it prints out errors correctly when run from CLI now that we return a struct instead of err? or do we print out the entire struct?

**Review by eytan-avisror — APPROVED** [review]
LGTM
